#!/usr/bin/env bash
# Orchestration for the public tunnel lab: one Cloudflare named tunnel fronts
# *.<domain>; tunnel/router.mjs dispatches host labels to local example ports.
# See tunnel/README.md for the full workflow.
set -euo pipefail

TUNNEL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TUNNEL_NAME="${TUNNEL_NAME:-epode-lab}"
ROUTER_PORT="${ROUTER_PORT:-8400}"
ROUTES_FILE="${TUNNEL_ROUTES_FILE:-$TUNNEL_DIR/routes.json}"
CONFIG_FILE="${TUNNEL_CONFIG_FILE:-$TUNNEL_DIR/config.yml}"
DEFAULTS_FILE="${TUNNEL_DEFAULTS_FILE:-$TUNNEL_DIR/routes.defaults.json}"
CERT_FILE="${CLOUDFLARED_CERT:-$HOME/.cloudflared/cert.pem}"

die() { echo "tunnel: $*" >&2; exit 1; }

require_cloudflared() {
  command -v cloudflared >/dev/null 2>&1 || die "cloudflared not installed; run: brew install cloudflared"
}

require_cert() {
  test -f "$CERT_FILE" || die "no Cloudflare cert at $CERT_FILE; run: cloudflared login"
}

seed_routes() {
  if test ! -f "$ROUTES_FILE"; then
    cp "$DEFAULTS_FILE" "$ROUTES_FILE"
    echo "tunnel: seeded $ROUTES_FILE from defaults"
  fi
}

# Prints "<tunnel-id> <credentials-file>" for the named tunnel, or nothing.
tunnel_record() {
  cloudflared tunnel list --output json 2>/dev/null | node -e '
    let raw = "";
    process.stdin.on("data", (chunk) => (raw += chunk)).on("end", () => {
      const name = process.argv[1];
      const match = JSON.parse(raw).find((tunnel) => tunnel.name === name && !tunnel.deleted_at);
      if (match) console.log(`${match.id} ${match.credentials_file ?? ""}`);
    });
  ' "$TUNNEL_NAME"
}

configured_domain() {
  test -f "$CONFIG_FILE" || return 0
  sed -n 's/^  - hostname: "\*\.//p' "$CONFIG_FILE" | head -1 | tr -d '"'
}

print_routes() {
  local domain="$1"
  node -e '
    const fs = require("node:fs");
    const [routesFile, domain] = process.argv.slice(1);
    let routes = {};
    try { routes = JSON.parse(fs.readFileSync(routesFile, "utf8")); } catch {}
    const entries = Object.entries(routes).sort(([a], [b]) => a.localeCompare(b));
    if (entries.length === 0) { console.log("  (no routes yet)"); process.exit(0); }
    for (const [name, port] of entries) {
      const url = domain ? `https://${name}.${domain}` : "(run tunnel-setup to assign a domain)";
      console.log(`  ${name.padEnd(16)} 127.0.0.1:${String(port).padEnd(6)} ${url}`);
    }
  ' "$ROUTES_FILE" "$domain"
}

cmd_setup() {
  local domain="${1:-}"
  test -n "$domain" || die "usage: tunnel.sh setup <base-domain>   (e.g. lab.example.com)"
  require_cloudflared
  require_cert
  seed_routes

  local record id creds
  record="$(tunnel_record || true)"
  if test -z "$record"; then
    echo "tunnel: creating named tunnel '$TUNNEL_NAME'"
    cloudflared tunnel create "$TUNNEL_NAME" >/dev/null
    record="$(tunnel_record)"
  fi
  test -n "$record" || die "could not resolve tunnel '$TUNNEL_NAME'"
  id="$(echo "$record" | cut -d' ' -f1)"
  creds="$(echo "$record" | cut -d' ' -f2)"
  test -n "$creds" && test -f "$creds" || creds="$HOME/.cloudflared/$id.json"
  test -f "$creds" || die "credentials file missing for tunnel $id"

  echo "tunnel: routing DNS *.$domain and $domain to $TUNNEL_NAME ($id)"
  cloudflared tunnel route dns --overwrite-dns "$TUNNEL_NAME" "*.$domain"
  cloudflared tunnel route dns --overwrite-dns "$TUNNEL_NAME" "$domain"

  cat > "$CONFIG_FILE" <<EOF
# Generated by tunnel.sh setup for $domain. Local state; do not commit.
tunnel: $id
credentials-file: $creds
ingress:
  - hostname: "*.$domain"
    service: http://127.0.0.1:$ROUTER_PORT
  - hostname: "$domain"
    service: http://127.0.0.1:$ROUTER_PORT
  - service: http_status:404
EOF
  echo "tunnel: wrote $CONFIG_FILE"
  echo ""
  echo "Setup complete. Next:"
  echo "  make tunnel-run            # start router + tunnel in the foreground"
  echo "  make tunnel-route NAME=demo PORT=4311"
  echo ""
  echo "IMPORTANT: https://$domain and all subdomains are now public."
  echo "Put Cloudflare Access in front of *.$domain before real testing:"
  echo "  https://one.dash.cloudflare.com/ -> Access -> Applications -> Add (self-hosted)"
}

cmd_route_add() {
  local name="${1:-}" port="${2:-}"
  test -n "$name" && test -n "$port" || die "usage: tunnel.sh route add <name> <port>"
  echo "$name" | grep -qE '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$' \
    || die "invalid name '$name' (lowercase DNS label, letters/digits/hyphens)"
  echo "$port" | grep -qE '^[0-9]+$' || die "invalid port '$port'"
  test "$port" -ge 1 && test "$port" -le 65535 || die "port '$port' out of range"
  seed_routes
  node -e '
    const fs = require("node:fs");
    const [file, name, port] = process.argv.slice(1);
    const routes = JSON.parse(fs.readFileSync(file, "utf8"));
    routes[name] = Number(port);
    fs.writeFileSync(file, `${JSON.stringify(routes, null, 2)}\n`);
  ' "$ROUTES_FILE" "$name" "$port"
  local domain
  domain="$(configured_domain)"
  echo "tunnel: $name -> 127.0.0.1:$port"
  if test -n "$domain"; then echo "tunnel: public URL https://$name.$domain"; fi
}

cmd_route_rm() {
  local name="${1:-}"
  test -n "$name" || die "usage: tunnel.sh route rm <name>"
  test -f "$ROUTES_FILE" || die "no routes file at $ROUTES_FILE"
  node -e '
    const fs = require("node:fs");
    const [file, name] = process.argv.slice(1);
    const routes = JSON.parse(fs.readFileSync(file, "utf8"));
    if (!(name in routes)) { console.error(`tunnel: no route named ${name}`); process.exit(1); }
    delete routes[name];
    fs.writeFileSync(file, `${JSON.stringify(routes, null, 2)}\n`);
  ' "$ROUTES_FILE" "$name"
  echo "tunnel: removed route '$name'"
}

cmd_route_ls() {
  local domain
  domain="$(configured_domain)"
  print_routes "$domain"
}

cmd_run() {
  require_cloudflared
  test -f "$CONFIG_FILE" || die "no $CONFIG_FILE; run: make tunnel-setup TUNNEL_DOMAIN=<domain>"
  seed_routes
  local domain
  domain="$(configured_domain)"

  if curl -sf -o /dev/null --max-time 1 "http://127.0.0.1:$ROUTER_PORT/" 2>/dev/null; then
    die "port $ROUTER_PORT is already serving HTTP; is the router already running?"
  fi

  node "$TUNNEL_DIR/router.mjs" --port "$ROUTER_PORT" --routes "$ROUTES_FILE" --base-domain "$domain" &
  local router_pid=$!
  trap 'kill "$router_pid" 2>/dev/null || true' EXIT INT TERM

  local attempt=0
  until curl -sf -o /dev/null --max-time 1 "http://127.0.0.1:$ROUTER_PORT/" 2>/dev/null; do
    attempt=$((attempt + 1))
    test "$attempt" -lt 50 || die "router failed to start on port $ROUTER_PORT"
    sleep 0.1
  done

  echo "tunnel: router on http://127.0.0.1:$ROUTER_PORT; routes live at:"
  print_routes "$domain"
  echo ""
  echo "tunnel: starting cloudflared (Ctrl-C stops both processes)"
  cloudflared tunnel --config "$CONFIG_FILE" run
}

cmd_status() {
  echo "cloudflared: $(command -v cloudflared >/dev/null 2>&1 && cloudflared --version 2>/dev/null | head -1 || echo 'not installed')"
  if test -f "$CERT_FILE"; then echo "login cert:  present ($CERT_FILE)"; else echo "login cert:  missing - run cloudflared login"; fi
  if command -v cloudflared >/dev/null 2>&1 && test -f "$CERT_FILE"; then
    local record
    record="$(tunnel_record || true)"
    if test -n "$record"; then echo "tunnel:      $TUNNEL_NAME ($(echo "$record" | cut -d' ' -f1))"; else echo "tunnel:      none - run make tunnel-setup"; fi
  fi
  echo "config:      $(test -f "$CONFIG_FILE" && echo "$CONFIG_FILE" || echo 'not generated')"
  echo "domain:      $(configured_domain || true)"
  if curl -sf -o /dev/null --max-time 1 "http://127.0.0.1:$ROUTER_PORT/" 2>/dev/null; then
    echo "router:      listening on $ROUTER_PORT"
  else
    echo "router:      not running"
  fi
  echo "routes:"
  cmd_route_ls
}

command="${1:-help}"
shift || true
case "$command" in
  setup) cmd_setup "$@" ;;
  route)
    sub="${1:-ls}"
    shift || true
    case "$sub" in
      add) cmd_route_add "$@" ;;
      rm|remove) cmd_route_rm "$@" ;;
      ls|list) cmd_route_ls "$@" ;;
      *) die "unknown route subcommand '$sub' (add|rm|ls)" ;;
    esac
    ;;
  run) cmd_run "$@" ;;
  status) cmd_status "$@" ;;
  help|--help|-h)
    sed -n '2,4p' "$0"
    echo "usage: tunnel.sh <setup <domain>|route add <name> <port>|route rm <name>|route ls|run|status>"
    ;;
  *) die "unknown command '$command' (setup|route|run|status)" ;;
esac
