import type { DashboardData } from "@/lib/api/dashboard";

export function dashboardFixture(overrides: Partial<DashboardData> = {}): DashboardData {
  const workspaceId = "11111111-1111-4111-8111-111111111111";
  const productId = "22222222-2222-4222-8222-222222222222";
  const environmentId = "33333333-3333-4333-8333-333333333333";
  const interactionId = "44444444-4444-4444-8444-444444444444";
  const sessionId = "55555555-5555-4555-8555-555555555555";
  const reportId = "66666666-6666-4666-8666-666666666666";
  const now = "2026-07-30T12:00:00Z";
  return {
    user: {
      id: "owner-user",
      displayName: "Owner User",
      email: "owner@example.com",
      handle: "owner",
    },
    workspace: {
      id: workspaceId,
      osUserId: "owner-user",
      name: "Epode Team",
      slug: "epode-team",
      feedbackMode: "never_ask",
      collectEventSummaries: false,
      retentionDays: 90,
      createdAt: now,
      updatedAt: now,
    },
    workspaceMemberships: [
      {
        workspaceId,
        workspaceName: "Epode Team",
        workspaceSlug: "epode-team",
        role: "owner",
      },
    ],
    currentRole: "owner",
    products: [
      {
        id: productId,
        workspaceId,
        name: "Search API",
        slug: "search-api",
        createdAt: now,
        updatedAt: now,
      },
    ],
    currentProduct: {
      id: productId,
      workspaceId,
      name: "Search API",
      slug: "search-api",
      createdAt: now,
      updatedAt: now,
    },
    environments: [
      {
        id: environmentId,
        workspaceId,
        productId,
        name: "Production",
        slug: "production",
        feedbackMode: "never_ask",
        collectEventSummaries: false,
        retentionDays: 90,
        createdAt: now,
        updatedAt: now,
      },
    ],
    currentEnvironment: {
      id: environmentId,
      workspaceId,
      productId,
      name: "Production",
      slug: "production",
      feedbackMode: "never_ask",
      collectEventSummaries: false,
      retentionDays: 90,
      createdAt: now,
      updatedAt: now,
    },
    activationMilestones: {
      workspaceId,
      productId,
      firstOpportunityAt: now,
      firstConfirmedInteractionAt: now,
      firstReportAt: now,
    },
    apiKeys: [
      {
        id: "77777777-7777-4777-8777-777777777777",
        environmentId,
        kind: "write",
        label: "Product key",
        prefix: "af_live_1234abcd",
        createdAt: now,
        expiresAt: null,
        lastUsedAt: now,
        revokedAt: null,
        interactionCount: 1,
        reportCount: 1,
      },
    ],
    interactions: [
      {
        id: interactionId,
        workspaceId,
        environmentId,
        apiKeyId: "77777777-7777-4777-8777-777777777777",
        sessionId,
        operation: "search",
        surface: "http",
        classification: "confirmed",
        confirmationMethod: "receipt",
        customerRef: "account-42",
        durationMs: 125,
        occurredAt: now,
        statusCode: 200,
        runtimeHint: "node",
        runtimeHintSource: "sdk",
        createdAt: now,
        updatedAt: now,
      },
    ],
    reports: [
      {
        id: reportId,
        interactionId,
        sessionId,
        summary: "Search results omitted the newest document",
        source: "agent",
        findings: [
          {
            kind: "bug",
            topic: "freshness",
            detail: "The document was indexed but not returned.",
            severity: "high",
          },
        ],
        impact: "degraded",
        confidence: 0.9,
        workaround: { used: true, detail: "Requested the document directly." },
        workflowStatus: "new",
        assigneeOsUserId: null,
        tags: [],
        internalNote: null,
        workflowUpdatedAt: null,
        operation: "search",
        surface: "http",
        classification: "confirmed",
        confirmationMethod: "receipt",
        customerRef: "account-42",
        durationMs: 125,
        occurredAt: now,
        statusCode: 200,
        runtimeHint: "node",
        runtimeHintSource: "sdk",
        createdAt: now,
      },
    ],
    sessions: [
      {
        id: sessionId,
        workspaceId,
        environmentId,
        refHint: "session-42",
        source: "sdk",
        startedAt: now,
        lastSeenAt: now,
        createdAt: now,
        interactionCount: 1,
        reportCount: 1,
        firstOperation: "search",
        lastOperation: "search",
        customerRef: "account-42",
        strongestImpact: "degraded",
      },
    ],
    insights: {
      windowDays: 30,
      comparisonDays: 30,
      reports: 1,
      opportunities: 1,
      confirmedInteractions: 1,
      confirmationRate: 100,
      reviewRate: 0,
      recentReports: 1,
      previousReports: 0,
      recentOpportunities: 1,
      previousOpportunities: 0,
      recentConfirmedInteractions: 1,
      previousConfirmedInteractions: 0,
      reportsWithBlockers: 0,
      reportsWithWorkarounds: 1,
      p50DurationMs: 125,
      p95DurationMs: 125,
      impacts: [{ name: "degraded", count: 1 }],
      findingKinds: [{ name: "bug", count: 1 }],
      topics: [{ name: "freshness", count: 1 }],
      blockingTopics: [],
      surfaces: [{ name: "http", count: 1 }],
      topOperations: [{ name: "search", count: 1 }],
    },
    listState: {
      interactionsLoaded: 1,
      interactionsTotal: 1,
      reportsLoaded: 1,
      reportsTotal: 1,
      sessionsLoaded: 1,
      sessionsTotal: 1,
    },
    teamMembers: [
      {
        osUserId: "owner-user",
        workspaceId,
        displayName: "Owner User",
        email: "owner@example.com",
        handle: "owner",
        role: "owner",
        joinedAt: now,
        updatedAt: now,
      },
      {
        osUserId: "member-user",
        workspaceId,
        displayName: "Member User",
        email: "member@example.com",
        handle: "member",
        role: "member",
        joinedAt: now,
        updatedAt: now,
      },
    ],
    teamInvitations: [],
    ...overrides,
  };
}
